### ISSUE TITLE
Segmentation fault in mTxmq when running testsuite

### ISSUE THREAD

**Issue by richford** [m-a-d-n-e-s-s/madness#24]
Running testsuite produces a segmentation fault in mTxmq when Testing 1-D separated operators.  @wsttiger, mTxmq is yours right?  Can anyone else using LLVM 6.0 reproduce this?

`(gdb) run` terminates with:
```
Test separated operators - type = std::complex<double> , ndim = 1 

timer:              project     0.00s     0.00s
         f norm is 1.00000000e+00
     f total error 4.27882902e-14
[New Thread 0x170b of process 92944]
[New Thread 0x1803 of process 92944]
[New Thread 0x1903 of process 92944]

Program received signal SIGSEGV, Segmentation fault.
0x000000010090b946 in madness::mTxmq<std::__1::complex<double>, double, std::__1::complex<double> > (dimi=4330568192, dimj=20, dimk=0, c=<optimized out>, a=<optimized out>, b=0x1021f3ae0) at mtxmq.cc:1383
1383	            __asm__ volatile
```

`(gdb) where` returns:
```
#0  0x000000010090b946 in madness::mTxmq<std::__1::complex<double>, double, std::__1::complex<double> > (dimi=4330568192, dimj=20, dimk=0, c=<optimized out>, a=<optimized out>, b=0x1021f3ae0) at mtxmq.cc:1383
#1  0x00000001000f5739 in madness::Tensor<madness::TensorResultType<std::__1::complex<double>, double>::type>& madness::fast_transform<std::__1::complex<double>, double>(madness::Tensor<std::__1::complex<double> > const&, madness::Tensor<double> const&, madness::Tensor<madness::TensorResultType<std::__1::complex<double>, double>::type>&, madness::Tensor<madness::TensorResultType<std::__1::complex<double>, double>::type>&) ()
#2  0x00000001000f4f45 in madness::Tensor<madness::TensorResultType<std::__1::complex<double>, double>::type> madness::transform<std::__1::complex<double>, double>(madness::Tensor<std::__1::complex<double> > const&, madness::Tensor<double> const&) ()
#3  0x000000010010d8a3 in madness::Convolution1D<std::__1::complex<double> >::nonstandard(int, long long) const ()
#4  0x000000010010cd41 in madness::SeparatedConvolution<std::__1::complex<double>, 1ul>::getmuop(int, int, madness::Key<1ul> const&) const ()
#5  0x000000010010528a in madness::SeparatedConvolution<std::__1::complex<double>, 1ul>::getop_ns(int, madness::Key<1ul> const&) const ()
#6  0x00000001000fe746 in double madness::FunctionImpl<std::__1::complex<double>, 1ul>::do_apply_directed_screening<madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const, std::__1::complex<double> >(madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const*, madness::Key<1ul> const&, madness::GenTensor<std::__1::complex<double> > const&, bool const&) ()
#7  0x00000001000fdc00 in madness::FunctionImpl<std::__1::complex<double>, 1ul>::recursive_apply_op2<madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const>::operator()(madness::Key<1ul> const&) const ()
#8  0x00000001000fd533 in madness::Void madness::FunctionImpl<std::__1::complex<double>, 1ul>::traverse_tree<madness::FunctionImpl<std::__1::complex<double>, 1ul>::recursive_apply_op2<madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const>, madness::noop<std::__1::complex<double>, 1ul> >(madness::FunctionImpl<std::__1::complex<double>, 1ul>::recursive_apply_op2<madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const> const&, madness::noop<std::__1::complex<double>, 1ul> const&, madness::Key<1ul> const&) const ()
#9  0x0000000100115eb7 in madness::TaskFn<madness::detail::MemFuncWrapper<madness::FunctionImpl<std::__1::complex<double>, 1ul> const*, madness::Void (madness::FunctionImpl<std::__1::complex<double>, 1ul>::*)(madness::FunctionImpl<std::__1::complex<double>, 1ul>::recursive_apply_op2<madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const> const&, madness::noop<std::__1::complex<double>, 1ul> const&, madness::Key<1ul> const&) const, madness::Void>, madness::Future<madness::FunctionImpl<std::__1::complex<double>, 1ul>::recursive_apply_op2<madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const> >, madness::noop<std::__1::complex<double>, 1ul>, madness::Key<1ul>, void, void, void, void, void, void>::run(madness::TaskThreadEnv const&) ()
#10 0x0000000100058119 in madness::PoolTaskInterface::run_multi_threaded() ()
#11 0x0000000100057d01 in madness::ThreadPool::run_task() ()
#12 0x000000010020a6c9 in madness::WorldTaskQueue::fence() ()
#13 0x0000000100924dde in madness::WorldGopInterface::fence (this=0x101f077a0) at worldgop.cc:67
#14 0x00000001000fcde2 in void madness::FunctionImpl<std::__1::complex<double>, 1ul>::recursive_apply<madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const>(madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const&, madness::FunctionImpl<std::__1::complex<double>, 1ul> const*, madness::FunctionImpl<std::__1::complex<double>, 1ul>*, bool) ()
#15 0x00000001000fbb44 in madness::Function<madness::TensorResultType<madness::SeparatedConvolution<std::__1::complex<double>, 1ul>::opT, std::__1::complex<double> >::type, 1ul> madness::apply_only<madness::SeparatedConvolution<std::__1::complex<double>, 1ul>, std::__1::complex<double>, 1ul>(madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const&, madness::Function<std::__1::complex<double>, 1ul> const&, bool) ()
#16 0x00000001000fa924 in madness::Function<madness::TensorResultType<madness::SeparatedConvolution<std::__1::complex<double>, 1ul>::opT, std::__1::complex<double> >::type, 1ul> madness::apply<madness::SeparatedConvolution<std::__1::complex<double>, 1ul>, std::__1::complex<double>, 1ul>(madness::SeparatedConvolution<std::__1::complex<double>, 1ul> const&, madness::Function<std::__1::complex<double>, 1ul> const&, bool) ()
#17 0x000000010001c015 in int test_op<std::__1::complex<double>, 1ul>(madness::World&) ()
#18 0x00000001000041ef in main (argc=1, argv=0x7fff5fbff910) at testsuite.cc:1316
```

`mpicxx -v` returns
```
mpicxx for MPICH version 3.1.2
Apple LLVM version 6.0 (clang-600.0.41.2) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
```

And I'm on a Macbook Pro with 8 GB 1600 MHz DDR3 memory and an Intel Core i5 processor.

**Comment by naromero77** [comment]
Adam,

Can this issue be closed?

**Comment by naromero77** [comment]
Talked to Justus. We don't really have enough information to reproduce this issue. We are going to close it for now, but Adam can re-open it.
